course/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path("course/",views.home,name="home"),
    path("course/<int:course_id>/",views.course_details,name="course_details"),
    path("course/<int:course_id>/<int:lesson_id>/", views.lesson_details, name="lesson_details"),
    path("membership/",views.course_membership,name="course_membership"),
    path("signin/",views.user_signup),
    path("login/",views.user_login),
    path("logout/", views.user_logout),
]

online_learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("course.urls")),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
MEMBERSHIP_TYPE = (("FREE", "free"),
                   ("PRO", "pro"),
                   ("ENTERPRISE", "enterprise"))


class Membership(models.Model):
    type = models.CharField(max_length=15, default="free", choices=MEMBERSHIP_TYPE)
    price = models.IntegerField()
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.type


class UserMembership(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    membership_type = models.ForeignKey(Membership, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.user_membership.user.username


class Course(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    allowed_membership = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=150)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    video = models.FileField(upload_to="media/videos/", null=True, blank=True)
    image = models.ImageField(upload_to="media/images/",blank=True,null=True)

    def __str__(self):
        return self.title

course/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect, get_object_or_404, get_list_or_404
from .models import Lesson, Course, Subscription, UserMembership, Membership
from django.contrib.auth.models import User


# Create your views here.
@login_required(login_url='/login/')
def home(request):
    courses = get_list_or_404(Course)
    return render(request, "course.html", {"courses": courses})


@login_required(login_url='/login/')
def course_details(request, course_id):
    # breakpoint()
    course = Course.objects.get(id=course_id)
    m_type = course.allowed_membership.all()
    lessons = course.lesson_set.all()
    return render(request, "course_details.html", {"course": course, "lessons": lessons, "type": m_type})


@login_required(login_url='/login/')
def lesson_details(request, course_id, lesson_id):
    course = Course.objects.get(id=course_id)
    lesson = course.lesson_set.get(id=lesson_id)
    return render(request, "lesson_details.html", {"lesson": lesson})


@login_required(login_url='/login/')
def course_membership(request):
    member_ships = Membership.objects.all()
    return render(request, "course_membership.html", {"memberships": member_ships})

























































def user_signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/course/')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/login/')
        else:
            return render(request, 'signin.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'signin.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect("/course/")
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/course/')
        else:
            form = AuthenticationForm(request.POST)
            return render(request, 'login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login/')

course/templates/course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>course list</title>
</head>
<body>
<div>
    <h3>COURSE LIST</h3>
</div>
{% if courses %}
    {% for course in courses %}
        {{forloop.counter}}
        <a href="{{course.id}}/">{{course}}</a><br>
    {% endfor %}
{% else %}
    NO COURSES THERE
{% endif%}
COURSES MEMBERSHIP LISE WISE : <a href="/membership/"><button>SELECT</button></a>
</body>
</html><br>
<a href="/logout/">logout</a>

course/templates/course_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>course_details</title>
</head>
<body>
COURSE TITLE : {{course.title}}<br>
<div>
    {% for t in type %}
        COURSE TYPE : {{t}}<br>
    {% endfor %}
    </div>
COURSE DESCRIPTION : {{course.description}}<br>
LESSONS :<br>
{% if lessons %}
    {% for lesson in lessons %}
    {{ forloop.counter }}
    <a href="{{lesson.id}}/">{{lesson.title}}</a><br>
    {% endfor %}
{% else %}
    NO LESSONS THERE
{% endif %}
</body>
</html>

course/templates/course_membership.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=2">
<style>
* {
  box-sizing: border-box;
}
.column {
  float: left;
  width: 50.33%;
  padding: 0px;
  height: 200px;
}
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>
<body>
<div class="container">
	<h2>Select a membership</h2>
	<div class="row">
		<div class="column">
			<div class="column">
				{% for object in memberships %}
				<h2>{{ object }}</h2>
				<p>Price: {{ object.price }}<small>/month</small></p>
				<h4>COURSE LIST</h4>
					<ol>
						{% for course in object.course_set.all %}
							<p><li><a href="/course/{{course.id}}/">{{ course.title }}</a></li></p>
						{% endfor %}
					</ol>
				<button>Enter</button>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

course/templates/lesson_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>lesson_details</title>
</head>
<body>
COURSE NAME : {{lesson.course}}<br>
LESSON : {{lesson.title}}<br>
UPLOAD DATE:{{lesson.date}}<br>
VIDEO :<br>
<video width="400" controls>
  <source src="/media/{{lesson.video}}" type="video/mp4">
  Your browser does not support HTML video.
</video>
<body/>
</html>

course/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>log_in</title>
</head>
<body>
<form action="." method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="save" value="save"/>
</form><br>
<a href="/signin/">signin</a>

</body>
</html>

course/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sign_in</title>
</head>
<body>
<form action="." method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="save" value="save"/>
</form><br>
<a href="/login/">login page</a>

</body>
</html>

course/templates/u.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{u.username}}
</body>
</html>